server:
  port: 8080
eureka:
    client:
       service-url:
          defaultZone: http://root:123456@localhost:8761/eureka/
    instance:
        prefer-ip-address: true
spring:
  application:
    name: microservice-config-server-eureka
  cloud:
    config:
      server:
        git:
          uri: git@github.com:1419659624/springcloud-config   # 配置Git仓库的地址