server:
   port: 8010
eureka:
    client:
       service-url:
          defaultZone: http://root:123456@localhost:8761/eureka/
    instance:
        prefer-ip-address: true
spring:
    application:
        name: microservice-consumer-movie-ribbon-properties-customizing
microservice-provider-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule