server:
    port: 8761
eureka:
    server:
       enable-self-preservation: false
    client:
       register-with-eureka: false
       fetch-registry: false
       service-url:
          defaultZone: http://root:123456@localhost:8761/eureka/
       healthcheck:
          enabled: true     
    instance:
        preferIpAddress: true
        instance-id: ${spring.cloud.client.ipAddress}:${spring.application.name}:${spring.application.instance_id:${server.port}}
security:
   basic:
       enabled: true
   user: 
       name: root
       password: 123456
