server:
    port: 8031
eureka:
    client:
      service-url:
        defaultZone: http://root:123456@localhost:8761/eureka/
    instance:
      prefer-ip-address: true
spring:
    application:
        name: microservice-hystrix-turbine
turbine:
   aggregator:
        clusterConfig: MICROSERVICE-CONSUMER-MOVIE-RIBBON-WITH-HYSTRIX
   appConfig: microservice-consumer-movie-ribbon-with-hystrix